services:

  consul:
    image: hashicorp/consul
    ports:
      - "8500:8500"
    command: "agent -dev -client=0.0.0.0"
    networks:
      - shared-network

  sidecar:
    image: sidecar
    build:
      context: .
      dockerfile: Sidecar/Dockerfile
    networks:
     - shared-network
  
networks:
  shared-network: